### ISSUE TITLE
Interactive documentation or blog post with interactive code snippets

### ISSUE THREAD

**Issue by viebel** [mgechev/javascript-algorithms#109]
Would you be interested by having an interactive documentation for `javascript-algorithms`?

You could use my [klipse plugin](https://github.com/viebel/klipse)

**Comment by mgechev** [comment]
Thanks, we will consider this!

**Comment by viebel** [comment]
@mgechev I forgot to mention that I'm the author of the [klipse plugin](https://github.com/viebel/klipse). So don't hesitate to let me know if you need help.

**Comment by mgechev** [comment]
I think you did mention it. Thanks for offering your help! I may write a series of blog posts at some point.
