### ISSUE TITLE
Something wrong with @param and @return

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#11]
Looks like we have a problem with @param and @return
All was OK in JSDoc 3.3.0-alpha13: http://andreygeonya.github.io/javascript-algorithms/docs/module-graphs_others_topological-sort.html
But gulp-jsdoc uses JSDoc 3.3.0-alpha5 and doesn't generate Parameters and Returns sections: https://mgechev.github.io/javascript-algorithms/topological-sort.html

**Comment by mgechev** [comment]
Closing it :-)
