### ISSUE TITLE
New algorithm suggestion.

### ISSUE THREAD

**Issue by krzysztof-grzybek** [mgechev/javascript-algorithms#111]
I would like to implement algorithm which finds [longest common subsequence](https://en.wikipedia.org/wiki/Longest_common_subsequence_problem). 

Now I can see in repository [longest-subsequence.js](https://github.com/mgechev/javascript-algorithms/blob/master/src/searching/longest-subsequence.js) file, which refers to [longest increasing subsequence problem](https://en.wikipedia.org/wiki/Longest_increasing_subsequence).

I suggest renaming [longest-subsequence.js](https://github.com/mgechev/javascript-algorithms/blob/master/src/searching/longest-subsequence.js) to "longest-increasing-subsequence.js" and add new longest-common-subsequence.js file.

What do You think about this idea? Of course I would make pull request with those changes.

**Comment by mgechev** [comment]
Yes, makes sense. I'd love to get a PR with the suggestion.
