### ISSUE TITLE
Bug in interval-tree.js

### ISSUE THREAD

**Issue by pkerpedjiev** [mgechev/javascript-algorithms#112]
Great library, but I think there's a bug in the `IntervalTree` implementation. Consider the following snippet:

```javascript
it = new IntervalTree()
it.add([10383734, 10594186])
it.add([9495571, 9677853])

it.add([9303743, 9404967])
it.intersects([9303743, 9303744])
```

This should logically return `true`, right? The intersection test clearly overlaps the last added interval. Running this, however, yields `false`. If either of the first two `add` statements are removed, the intersection check at the end returns `true` as expected.

**Comment by mgechev** [comment]
Yes, it seems like there's an issue. I'll take a look at the implementation when I find some spare time. A PR will also be appreciated, if you don't mind digging into the code.

**Comment by pkerpedjiev** [comment]
Added a PR (#114) with a fix and some tests. Seems to work for me.
