### ISSUE TITLE
Implement CYK?

### ISSUE THREAD

**Issue by ysharplanguage** [mgechev/javascript-algorithms#117]
Hi,

I'm thinking of porting my [CNF grammar data structure and CYK parser implementation in C#](https://github.com/ysharplanguage/CJ2/blob/master/Program.cs) to JS.

Let me know if interested. You may want to check out the [ATIS grammar example / test input](https://github.com/ysharplanguage/CJ2/tree/master/Tests), which is the less toy-ish one I've got (working)\* so far -- ie, beyond [Wikipedia's example](https://en.wikipedia.org/wiki/CYK_algorithm#Example), etc.

Cheers,
CJ

\* (it parses OK 73% (72 out of 98) of the sample English sentences)

**Comment by mgechev** [comment]
Hey @ysharplanguage sounds good! The algorithm will verify if given string belongs to the language defined by the grammar and produce an AST?

**Comment by ysharplanguage** [comment]
@mgechev yes, of course, and it yelds the parse forest (for ambiguous grammars) by having the matrix's cells filled with the one or more non-terminals that CYK can reduce to. Cf. the call site to the HashSet's UnionWith method in the C#. Just run the thing when you get a chance. Don't miss the notes.txt.

Cheers,
CJ

**Comment by ysharplanguage** [comment]
Please ignore all the so-called "CJ2" related code lines. Those are just my own experimental algo I'm toying with (it has only the CNF grammar data structure usage in common with the CYK classic).

**Comment by mgechev** [comment]
Would love to get a PR with the implementation and the corresponding specs!

**Comment by ysharplanguage** [comment]
@mgechev  Cool, then :) Actually, I'm curious, too, to see what that'd give in JS.

We'll see :)

**Comment by mgechev** [comment]
Lets close the issue for now until there are some updates.
