### ISSUE TITLE
Wanna contribute but can not see proper guide for contribute

### ISSUE THREAD

**Issue by jsroyal** [mgechev/javascript-algorithms#124]
Hi! Javascripter with CSE,
I would like to also contribute but do not see contribute.md.
Please anybody can help me to init guide.

**Comment by mgechev** [comment]
Hey @jsroyal, great to hear you're willing to help the project! You can open an issue with a suggestion for a missing algorithm. Right after that just make sure you have tests and the CI build passes.

Thanks again!
