### ISSUE TITLE
Copy/Paste in graphs

### ISSUE THREAD

**Issue by AndriiHeonia** [mgechev/javascript-algorithms#13]
Looks like it is possible to make graphs module better according to DRY approach.

For example `Edge` class used in Prism algorithm and in Bellman–Ford algorithm and it was copy/pasted.

Maybe there is reason to make `Graph` data structure with edges and vertices inside `data-structures` folder and algorithms inside `graphs` folder will just process this graph?

**Comment by mgechev** [comment]
Yes, agree.
