### ISSUE TITLE
Complete "When to use" section && add README.md file in all src/* folders

### ISSUE THREAD

**Issue by BitYog** [mgechev/javascript-algorithms#131]
Hey @mgechev,
I noticed that you have a README.md file in src/sorting, which has the Big O complexity for all algorithms. It also has the "When to use" column, which is blank. Basecs already has many algorithms' explanations, and can be used to fill in this.column. The explanations are valid for most languages and are concise. 

Also, a README.md for all src/* folders would be helpful. (I would like to work on this)

**Comment by mgechev** [comment]
Sounds good!

**Comment by leomaurodesenv** [comment]
Can have translated to other languages too?
I'm Brazilian, i can translate to Portuguese. 
This `javascript-algorithms` is pretty good.. can be accessible for anyone.

**Comment by BitYog** [comment]
@mgechev Thanks! Working on it now.
@leomaurodesenv I'm not an expert in languages, but there could be translated versions.

**Comment by BitYog** [comment]
Due to having done mistakes while commiting big changes, I'm going to resolve this issue by doing small commits, in three phases:

- [ ] Add Basecs articles for src/sorting (As it already has a README)
- [ ] Add README.md files for all src/* folders
- [ ] Add relevant Basecs articles
