### ISSUE TITLE
bug in avl tree data structure

### ISSUE THREAD

**Issue by GreedyBlade** [mgechev/javascript-algorithms#139]
Remove operation in avl tree does not work.
1. The remove function accepts a param with Number or String value, but in the line 605 ` return this.remove(min);` will pass a Node param to this function.
2. In _getNodesToRestructureRemove function, line 114, `y = (z._left === y) ? z._right : z._left;`, this condition `z._left === y` is always false

**Comment by yuzhouChen** [comment]
Can I try to fix it
