### ISSUE TITLE
Linkedlist remove  method has issue

### ISSUE THREAD

**Issue by rthangam** [mgechev/javascript-algorithms#146]
The linkedlist data structure compares data like this 

if (temp.data === data) {

to compare data which won't work. Either we need to recurse and compare all properties or use thirdparty library like lodash or underscore etc to do this. Please fix it.

**Comment by mgechev** [comment]
The best solution in this case is to provide a comparator function which accepts two objects and returns a boolean result.

I'd not mind keeping the reference check since it clearly demonstrates the data structure without introducing additional complexity.

Would you want to open a PR?

**Comment by rthangam** [comment]
Thanks for the response. Sure if you can.

**Comment by brunob15** [comment]
Hi Minko! I can open a PR for this if you want.

**Comment by mgechev** [comment]
Hey @brunob15, sure!

**Comment by brunob15** [comment]
Minko, I'm working on Windows and I'm getting errors about the linebreak style from gulp-eslint when running npm run build.
What do you suggest to do?

![image](https://user-images.githubusercontent.com/5839627/63231481-9f473080-c1f2-11e9-87fe-f8b0e5d12c5d.png)

**Comment by mgechev** [comment]
Feel free to disable this eslint rule.

**Comment by brunob15** [comment]
Great! I already created a PR :) Thank you
