### ISSUE TITLE
Code issue in LZW.js  ?

### ISSUE THREAD

**Issue by rthangam** [mgechev/javascript-algorithms#148]
I see this file has `exports.LZW.compress` and `exports.LZW.decompress` methods which are not prototypes? Ideally it should have been defined as`exports.LZW.prototype.compress` and `exports.LZW.prototype.decompress` ?

Also decompress won't return back the compressed data ?

> var lzw = new LZW();
undefined
var compressed = lzw.compress("ABCABCABCABCABCABC");
undefined
compressed
(9) [65, 66, 67, 256, 258, 257, 259, 262, 257]
var decompress = lzw.decompress(compressed);
undefined
decompress
"ABCĀĂāăĆā"

**Comment by mgechev** [comment]
Since `LZW` doesn't hold any state and we don't instantiate any objects we don't need to add the methods to the prototype.

**Comment by rthangam** [comment]
Thanks
