### ISSUE TITLE
Too deep namespace

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#30]
Inside 'searching' folder we have subfolders with just one js file. Maybe better to make folder structure not so deep like this:

searching/
-- binarysearch.js
-- recursive-binarysearch.js
-- knuth-morris-pratt.js
-- longest-increasing-subsequence.js
-- quickselect.js
-- maximum-subarray-divide-and-conquer.js
-- maximum-subarray.js

?

**Comment by mgechev** [comment]
Ok, lets do it this way.
