### ISSUE TITLE
Knuth-morris-pratt doesn't work

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#33]
Knuth-morris-pratt algorithm freezes and doesn't return any result. My code:

    var indexOf = require('../src/searching/knuth-morris-pratt').kmp;
    console.log(indexOf('hello', 'll'));

**Comment by mgechev** [comment]
Thanks! I'm going to take a look today or tomorrow.

**Comment by mgechev** [comment]
The issue should be already fixed.

[Here are](https://github.com/mgechev/javascript-algorithms/blob/master/test/searching/knuth-morris-pratt.spec.js) test cases I added. If you think that any other test case might be useful, please let me know.
