### ISSUE TITLE
broken mergesort jsdoc

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#40]
Hi @secrettriangle 

It looks like after your pull-request #39 documentation for the mergesort has been broken: https://mgechev.github.io/javascript-algorithms/ See: http://usejsdoc.org/howto-commonjs-modules.html#properties-of-the-exports-object 

Can you fix it?

**Comment by secrettriangle** [comment]
Hi @AndreyGeonya I ran `gulp jsdoc` and it seems to exit without error. Am I testing the jsdoc wrong?

**Comment by AndreyGeonya** [comment]
It will not show you any errors, `gulp jsdoc` just can't recognize your text as valid jsdoc and skips it.
