### ISSUE TITLE
mergesort example

### ISSUE THREAD

**Issue by AndreyGeonya** [mgechev/javascript-algorithms#42]
All algorithms are covered by example, except mergesort (it looks like in mergesort it has been missed after refactoring #39 by @secrettriangle ). https://mgechev.github.io/javascript-algorithms/module-sorting_mergesort.html

Also small enhacements:
* type names of each parameter in all documentation begins from uppercase;
* description of each parameter contains "." in the end.

**Comment by mgechev** [comment]
Yes, makes sense. I'm going to fix this today.
