### ISSUE TITLE
image url in readme is broken.

### ISSUE THREAD

**Issue by Jakehp** [mgechev/javascript-algorithms#48]
https://camo.githubusercontent.com/50d06cb4de159eb546690745bfb0ff01e3cd22c4/68747470733a2f2f7472617669732d63692e6f72672f6d6765636865762f6a6176617363726970742d616c676f726974686d732e7376673f6272616e63683d6d6173746572

**Comment by mgechev** [comment]
Travis-CI is under maintenance right now.

**Comment by Jakehp** [comment]
doh!
