### ISSUE TITLE
Noting the source of the ported implementation

### ISSUE THREAD

**Issue by Ahimta** [mgechev/javascript-algorithms#53]
Some algorithms, obviously, are inspired by or ported from Robert Sedgewick Java implementations (e.g: unionfind, LLRBT).

Would it not be more appropriate to add a comment mentioning this.

**Comment by mgechev** [comment]
I wouldn't say that they are ported but they are definitely inspired by Robert Sedgewick.

Later today I will update the description of quick find and quick union.
