### ISSUE TITLE
Levenstein computation does not cache results, leads to exponential complexity

### ISSUE THREAD

**Issue by adnanaziz** [mgechev/javascript-algorithms#56]
You can still use recursion, keep a cache (global or passed down), or do bottom up dynamic programming, e.g., like we did here: https://github.com/epibook/epibook.github.io/blob/master/solutions/cpp/Levenshtein_distance.cc

**Comment by mgechev** [comment]
I agree that it's worth optimizing. I'll keep the issue open in order to remind us to push a better implementation when we're available.

**Comment by mgechev** [comment]
Lets close this issue for now, although PRs are welcome performance is not essential for the learning purpose that this project has.
