### ISSUE TITLE
Can't clone repo as instructed by readme.md

### ISSUE THREAD

**Issue by mayankasthana** [mgechev/javascript-algorithms#60]
Running the command `git clone git@github.com:mgechev/javascript-algorithms.git javascript-algorithms-docs` from `readme.md` results in the following output-
    
    git clone git@github.com:mgechev/javascript-algorithms.git javascript-algorithms-docs
    Cloning into 'javascript-algorithms-docs'...
    Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

I tried changing the git clone URL to `https://github.com/mgechev/javascript-algorithms.git` and it worked.
Should I send a pull request to change the clone URL?

**Comment by mgechev** [comment]
If you have registered your public key properly you should to have this problem.

However, it is better to change the url to `https://github.com/mgechev/javascript-algorithms.git` since it will work in the general case :-)

**Comment by arthurvr** [comment]
This is a problem with your local setup, we honestly shouldn't really care about that. Though github's preference these days is https so yeah let's change it :)

**Comment by Jakehp** [comment]
Check [this](https://help.github.com/articles/generating-ssh-keys/) out @mayankasthana if you want to keep using SSH.

**Comment by Jakehp** [comment]
https://github.com/mgechev/javascript-algorithms/pull/61

**Comment by mayankasthana** [comment]
Thanks
