### ISSUE TITLE
Handle collision in the HashMap

### ISSUE THREAD

**Issue by mgechev** [mgechev/javascript-algorithms#66]
In case of generation of the same hash code for two different keys the collisions should be handled (using list?).

**Comment by mgechev** [comment]
@FilipeFalcaoBatista do you want to take this one?

**Comment by FilipeFalcaoBatista** [comment]
For sure

**Comment by FilipeFalcaoBatista** [comment]
@mgechev can you assign me to this issue?

**Comment by mgechev** [comment]
I won't be able to do that if you're not a project collaborator. Here is an [open feature request for this](https://github.com/isaacs/github/issues/100).

**Comment by Jakehp** [comment]
This isn't really necessary, since hash table was removed.
