### ISSUE TITLE
Add spec for hash-table data structure.

### ISSUE THREAD

**Issue by Jakehp** [mgechev/javascript-algorithms#69]
Dependent on https://github.com/mgechev/javascript-algorithms/issues/66

**Comment by mgechev** [comment]
Once #68 is merged we can proceed.

**Comment by Jakehp** [comment]
https://github.com/mgechev/javascript-algorithms/issues/73

**Comment by Jakehp** [comment]
https://github.com/mgechev/javascript-algorithms/blob/master/test/data-structures/hash-table.spec.js
