### ISSUE TITLE
publish to npm?

### ISSUE THREAD

**Issue by joshgillies** [mgechev/javascript-algorithms#81]
Really great work here! Just wondering whether this is likely to be published at some point soon?

**Comment by mgechev** [comment]
Thank you! I don't have such plans. I feel its publishing is against the [npm philosophy](https://www.npmjs.com/package/module-best-practices#small-focus). However, Addy Osmani published a few packages ([bubble sort](https://github.com/addyosmani/bubblesort), [recursive binary search](https://github.com/addyosmani/recursive-binarysearch), [https://github.com/addyosmani/selectionsort](selection sort) and may be [others](https://github.com/addyosmani)) based on implementations in this repository.

**Comment by joshgillies** [comment]
Oh perfect! Thanks for the reply. I'll take a look over what's on npm to see what dedicated modules there are for these sort of algorithms. In the mean time I'll also continue to learn from the code here. :+1:  Closing.
