### ISSUE TITLE
Implement size/weight balanced tree for dynamic array.

### ISSUE THREAD

**Issue by lygstate** [mgechev/javascript-algorithms#88]
The array should be able to do  the following operations:
Access the i-th element.
Insert element at potion i
Remove element from postion i.

All the operations should be strict O(logN);

**Comment by mgechev** [comment]
We have a couple of balanced tree, do you want to build an abstraction on top of any of them?

**Comment by lygstate** [comment]
@mgechev I've seen that, red-black-tree & avl-tree.

**Comment by mgechev** [comment]
Okay, lets keep the issue open for now. Unfortunately, I won't be able to start working on weight/size-balanced tree next a couple of weeks.

**Comment by lygstate** [comment]
@mgechev  It's OK, cause I am working on it
https://en.wikipedia.org/wiki/Weight-balanced_tree

**Comment by lygstate** [comment]
@mgechev  http://web.stanford.edu/~cqf/SBT.zip
I am not so sure if this algorithm is proof-OK.

**Comment by mgechev** [comment]
Sounds awesome! We're looking forward for it!

**Comment by Jakehp** [comment]
:+1:

**Comment by lygstate** [comment]
@Jakehp I've already implemented of it.

**Comment by Jakehp** [comment]
Am I blind? I don't see it.

But if you did we should probably close this.
