### ISSUE TITLE
Difficulty with running test

### ISSUE THREAD

**Issue by hsavit1** [mgechev/javascript-algorithms#89]
Hey,

can someone clarify this for me? I'm just trying to run the test file. I copied over the gulpfile.js into my project and did an npm install. I then did the `gulp test` and I'm getting the following result (which clearly didn't run the tests). Am I missing a step? Thanks in advance

➜  algorithms  gulp test
[17:03:09] Using gulpfile ~/node_modules/algorithms/gulpfile.js
[17:03:09] Starting 'test'...
0 specs, 0 failures
Finished in 0 seconds
[17:03:09] Finished 'test' after 53 ms

**Comment by mgechev** [comment]
> I copied over the gulpfile.js into my project and did an npm install

What is your project? This gulpfile is developed for the javascript-algorithms repository so most likely it won't work with any other projects.

What npm version are you using?
