### ISSUE TITLE
Version without solutions?

### ISSUE THREAD

**Issue by hschoenburg** [mgechev/javascript-algorithms#90]
Hey, I'm putting together a coding curriculum, and these algorithms are awesome. I was wondering if there exists a version of the code without the solutions already written?

**Comment by mgechev** [comment]
Hey @hschoenburg, I'm glad the repo is useful for teaching.

We haven't build the repo with the idea in mind to define different problems but more like to find the implementation of the individual algorithms.

However, you can define problems, which could be solved as composition of these algorithms. The solutions will require combination of the algorithms with slight modification which seems like a good exercise to me :-)
