### ISSUE TITLE
Enhancement suggestion

### ISSUE THREAD

**Issue by ysharplanguage** [mgechev/javascript-algorithms#93]
Hi all,

Although I know the XSLT (1.0) processing model isn't per se a "classic computer science" algorithm, I was just curious if there'd be any interest for this repo to include a simple, quite minimalistic (yet useful, I believe) JavaScript equivalent? FWIW, it also nicely happens to be purely functional (i.e., side effects-free) -- that is, modulo only a couple String and Array prototype augmentations (helpers) that could be easily moved out into their own scope / namespace, if so wished.

For some working examples, see this SO link:

[http://stackoverflow.com/a/35663358/1409653](http://stackoverflow.com/a/35663358/1409653)

Let me know, &

Cheers,

**Comment by mgechev** [comment]
Sounds like an interesting idea. Such algorithm could be pushed to "[others](https://github.com/mgechev/javascript-algorithms/tree/master/src/others)".

I saw your implementation on jsfiddle, the only suggestion (as you already pointed) will be to not extend built-in objects.

**Comment by ysharplanguage** [comment]
Thanks for the feedback. Ok, I'll refactor it in that direction before making the pull request.

**Comment by ysharplanguage** [comment]
Here's a fiddle of the same combined examples, using the new API I'm contemplating:

[https://jsfiddle.net/YSharpLanguage/c7usrpsL](https://jsfiddle.net/YSharpLanguage/c7usrpsL)

Basically, it's all baked into just one function, "function Per(subject) { ... }" which forks on the type of its unique argument, to implement, either:

1) nodeset creation / selection / flattening / grouping / ordering / etc if subject is an array (only the returned array instance of the call to Per(someArray) is extended, not Array.prototype)
2) string interpolation, if subject is a string (it returns an object with a method "map(source)", which is bound to the subject)
3) XSLT look-alike transformation is the subject is a hash with a "$" member providing the array of rewriting rules (same as (2), returns an object with a method "map(source [, ruleName])" -- where "ruleName" is thus optional and provides functionality similar to <xsl:call-template name="templateName">...)
4) the identity function in all other cases

Cheers,

**Comment by mgechev** [comment]
@ysharplanguage lets stick to traditional CS algorithms for now. Sorry for the delayed response.

If you're interested into contributing a few missing algorithms & data structures are:

- Fibonacci heap.
- Deletion in the Red-Black Tree.
- KDTrees.
- Etc...
